version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: blacktop/kafka:3.0.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=changeit
