apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: {{ .Values.replicas }}
  template: # orange
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent # Always, IfNotPresent, Never
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1.5G
        livenessProbe: # if failed, kill pod
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe: # if failed, close network traffic
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
